# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike_2\Eclipse workspace\LLP\src\llp.ui'
#
# Created: Fri Jan 27 20:49:41 2012
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(511, 265)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(511, 265))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 265))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.leftFrame = QtGui.QFrame(self.centralwidget)
        self.leftFrame.setFrameShape(QtGui.QFrame.Panel)
        self.leftFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.leftFrame.setObjectName(_fromUtf8("leftFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.leftFrame)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.leftFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.volumeSlider.setMaximumSize(QtCore.QSize(44, 10000))
        self.volumeSlider.setMaximumVolume(1.0)
        self.volumeSlider.setOrientation(QtCore.Qt.Vertical)
        self.volumeSlider.setMuteVisible(True)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.verticalLayout.addWidget(self.volumeSlider)
        self.horizontalLayout_5.addWidget(self.leftFrame)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.timeFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeFrame.sizePolicy().hasHeightForWidth())
        self.timeFrame.setSizePolicy(sizePolicy)
        self.timeFrame.setMinimumSize(QtCore.QSize(0, 25))
        self.timeFrame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.timeFrame.setFrameShape(QtGui.QFrame.Panel)
        self.timeFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.timeFrame.setObjectName(_fromUtf8("timeFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.timeFrame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.positionIndicator = QtGui.QLabel(self.timeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionIndicator.sizePolicy().hasHeightForWidth())
        self.positionIndicator.setSizePolicy(sizePolicy)
        self.positionIndicator.setMinimumSize(QtCore.QSize(0, 20))
        self.positionIndicator.setMaximumSize(QtCore.QSize(16777215, 20))
        self.positionIndicator.setObjectName(_fromUtf8("positionIndicator"))
        self.horizontalLayout_2.addWidget(self.positionIndicator)
        self.dividerLabel = QtGui.QLabel(self.timeFrame)
        self.dividerLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.dividerLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.dividerLabel.setObjectName(_fromUtf8("dividerLabel"))
        self.horizontalLayout_2.addWidget(self.dividerLabel)
        self.totalLabel = QtGui.QLabel(self.timeFrame)
        self.totalLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.totalLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.totalLabel.setObjectName(_fromUtf8("totalLabel"))
        self.horizontalLayout_2.addWidget(self.totalLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.timeFrame)
        self.centerFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerFrame.sizePolicy().hasHeightForWidth())
        self.centerFrame.setSizePolicy(sizePolicy)
        self.centerFrame.setMinimumSize(QtCore.QSize(457, 128))
        self.centerFrame.setMaximumSize(QtCore.QSize(1000, 1000))
        self.centerFrame.setFrameShape(QtGui.QFrame.Panel)
        self.centerFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.centerFrame.setObjectName(_fromUtf8("centerFrame"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centerFrame)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.buttonFrame = QtGui.QFrame(self.centerFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFrame.sizePolicy().hasHeightForWidth())
        self.buttonFrame.setSizePolicy(sizePolicy)
        self.buttonFrame.setMinimumSize(QtCore.QSize(30, 122))
        self.buttonFrame.setMaximumSize(QtCore.QSize(30, 122))
        self.buttonFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.buttonFrame.setObjectName(_fromUtf8("buttonFrame"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.buttonFrame)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.loopButton = QtGui.QPushButton(self.buttonFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loopButton.sizePolicy().hasHeightForWidth())
        self.loopButton.setSizePolicy(sizePolicy)
        self.loopButton.setMinimumSize(QtCore.QSize(28, 24))
        self.loopButton.setMaximumSize(QtCore.QSize(28, 24))
        self.loopButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Once")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Loop")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Loop")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Once")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.loopButton.setIcon(icon)
        self.loopButton.setCheckable(True)
        self.loopButton.setObjectName(_fromUtf8("loopButton"))
        self.verticalLayout_7.addWidget(self.loopButton)
        self.selectionButton = QtGui.QPushButton(self.buttonFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionButton.sizePolicy().hasHeightForWidth())
        self.selectionButton.setSizePolicy(sizePolicy)
        self.selectionButton.setMinimumSize(QtCore.QSize(28, 24))
        self.selectionButton.setMaximumSize(QtCore.QSize(28, 24))
        self.selectionButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Whole Song")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Selection")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Selection")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Whole Song")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.selectionButton.setIcon(icon1)
        self.selectionButton.setCheckable(True)
        self.selectionButton.setObjectName(_fromUtf8("selectionButton"))
        self.verticalLayout_7.addWidget(self.selectionButton)
        self.trackButton = QtGui.QPushButton(self.buttonFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackButton.sizePolicy().hasHeightForWidth())
        self.trackButton.setSizePolicy(sizePolicy)
        self.trackButton.setMinimumSize(QtCore.QSize(28, 24))
        self.trackButton.setMaximumSize(QtCore.QSize(28, 24))
        self.trackButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Unlink")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Link")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Link")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Unlink")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.trackButton.setIcon(icon2)
        self.trackButton.setCheckable(True)
        self.trackButton.setObjectName(_fromUtf8("trackButton"))
        self.verticalLayout_7.addWidget(self.trackButton)
        self.zoomInButton = QtGui.QPushButton(self.buttonFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomInButton.sizePolicy().hasHeightForWidth())
        self.zoomInButton.setSizePolicy(sizePolicy)
        self.zoomInButton.setMinimumSize(QtCore.QSize(28, 24))
        self.zoomInButton.setMaximumSize(QtCore.QSize(28, 24))
        self.zoomInButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Zoom In")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInButton.setIcon(icon3)
        self.zoomInButton.setObjectName(_fromUtf8("zoomInButton"))
        self.verticalLayout_7.addWidget(self.zoomInButton)
        self.zoomOutButton = QtGui.QPushButton(self.buttonFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomOutButton.sizePolicy().hasHeightForWidth())
        self.zoomOutButton.setSizePolicy(sizePolicy)
        self.zoomOutButton.setMinimumSize(QtCore.QSize(28, 24))
        self.zoomOutButton.setMaximumSize(QtCore.QSize(28, 24))
        self.zoomOutButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Zoom Out")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutButton.setIcon(icon4)
        self.zoomOutButton.setObjectName(_fromUtf8("zoomOutButton"))
        self.verticalLayout_7.addWidget(self.zoomOutButton)
        self.horizontalLayout_7.addWidget(self.buttonFrame)
        self.viewFrame = QtGui.QFrame(self.centerFrame)
        self.viewFrame.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewFrame.sizePolicy().hasHeightForWidth())
        self.viewFrame.setSizePolicy(sizePolicy)
        self.viewFrame.setMinimumSize(QtCore.QSize(394, 122))
        self.viewFrame.setMaximumSize(QtCore.QSize(16777215, 122))
        self.viewFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.viewFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.viewFrame.setObjectName(_fromUtf8("viewFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.viewFrame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.markView = QtGui.QGraphicsView(self.viewFrame)
        self.markView.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.markView.sizePolicy().hasHeightForWidth())
        self.markView.setSizePolicy(sizePolicy)
        self.markView.setMinimumSize(QtCore.QSize(394, 100))
        self.markView.setMaximumSize(QtCore.QSize(1000, 100))
        self.markView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.markView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.markView.setObjectName(_fromUtf8("markView"))
        self.verticalLayout_3.addWidget(self.markView)
        self.globalView = QtGui.QGraphicsView(self.viewFrame)
        self.globalView.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalView.sizePolicy().hasHeightForWidth())
        self.globalView.setSizePolicy(sizePolicy)
        self.globalView.setMinimumSize(QtCore.QSize(394, 20))
        self.globalView.setMaximumSize(QtCore.QSize(1000, 20))
        self.globalView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.globalView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.globalView.setObjectName(_fromUtf8("globalView"))
        self.verticalLayout_3.addWidget(self.globalView)
        self.horizontalLayout_7.addWidget(self.viewFrame)
        self.markFrame = QtGui.QFrame(self.centerFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.markFrame.sizePolicy().hasHeightForWidth())
        self.markFrame.setSizePolicy(sizePolicy)
        self.markFrame.setMinimumSize(QtCore.QSize(30, 122))
        self.markFrame.setMaximumSize(QtCore.QSize(30, 122))
        self.markFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.markFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.markFrame.setObjectName(_fromUtf8("markFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.markFrame)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.setBeginButton = QtGui.QPushButton(self.markFrame)
        self.setBeginButton.setMinimumSize(QtCore.QSize(28, 24))
        self.setBeginButton.setMaximumSize(QtCore.QSize(28, 24))
        self.setBeginButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/SetBegin")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setBeginButton.setIcon(icon5)
        self.setBeginButton.setObjectName(_fromUtf8("setBeginButton"))
        self.verticalLayout_5.addWidget(self.setBeginButton)
        self.prevMarkButton = QtGui.QPushButton(self.markFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMarkButton.sizePolicy().hasHeightForWidth())
        self.prevMarkButton.setSizePolicy(sizePolicy)
        self.prevMarkButton.setMinimumSize(QtCore.QSize(28, 24))
        self.prevMarkButton.setMaximumSize(QtCore.QSize(28, 24))
        self.prevMarkButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/PreviousMark")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevMarkButton.setIcon(icon6)
        self.prevMarkButton.setObjectName(_fromUtf8("prevMarkButton"))
        self.verticalLayout_5.addWidget(self.prevMarkButton)
        self.markButton = QtGui.QPushButton(self.markFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.markButton.sizePolicy().hasHeightForWidth())
        self.markButton.setSizePolicy(sizePolicy)
        self.markButton.setMinimumSize(QtCore.QSize(28, 24))
        self.markButton.setMaximumSize(QtCore.QSize(28, 24))
        self.markButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Mark")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markButton.setIcon(icon7)
        self.markButton.setObjectName(_fromUtf8("markButton"))
        self.verticalLayout_5.addWidget(self.markButton)
        self.nextMarkButton = QtGui.QPushButton(self.markFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextMarkButton.sizePolicy().hasHeightForWidth())
        self.nextMarkButton.setSizePolicy(sizePolicy)
        self.nextMarkButton.setMinimumSize(QtCore.QSize(28, 24))
        self.nextMarkButton.setMaximumSize(QtCore.QSize(28, 24))
        self.nextMarkButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/NextMark")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextMarkButton.setIcon(icon8)
        self.nextMarkButton.setObjectName(_fromUtf8("nextMarkButton"))
        self.verticalLayout_5.addWidget(self.nextMarkButton)
        self.setEndButton = QtGui.QPushButton(self.markFrame)
        self.setEndButton.setMinimumSize(QtCore.QSize(28, 24))
        self.setEndButton.setMaximumSize(QtCore.QSize(28, 24))
        self.setEndButton.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/SetEnd")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setEndButton.setIcon(icon9)
        self.setEndButton.setObjectName(_fromUtf8("setEndButton"))
        self.verticalLayout_5.addWidget(self.setEndButton)
        self.horizontalLayout_7.addWidget(self.markFrame)
        self.verticalLayout_2.addWidget(self.centerFrame)
        self.controlsFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsFrame.sizePolicy().hasHeightForWidth())
        self.controlsFrame.setSizePolicy(sizePolicy)
        self.controlsFrame.setMinimumSize(QtCore.QSize(0, 42))
        self.controlsFrame.setMaximumSize(QtCore.QSize(1000, 42))
        self.controlsFrame.setFrameShape(QtGui.QFrame.Panel)
        self.controlsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.controlsFrame.setObjectName(_fromUtf8("controlsFrame"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.controlsFrame)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.startButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(44, 40))
        self.startButton.setMaximumSize(QtCore.QSize(44, 40))
        self.startButton.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Start")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon10)
        self.startButton.setIconSize(QtCore.QSize(32, 32))
        self.startButton.setFlat(True)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_9.addWidget(self.startButton)
        self.rewindButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rewindButton.sizePolicy().hasHeightForWidth())
        self.rewindButton.setSizePolicy(sizePolicy)
        self.rewindButton.setMinimumSize(QtCore.QSize(44, 40))
        self.rewindButton.setMaximumSize(QtCore.QSize(44, 40))
        self.rewindButton.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Rewind")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindButton.setIcon(icon11)
        self.rewindButton.setIconSize(QtCore.QSize(32, 32))
        self.rewindButton.setFlat(True)
        self.rewindButton.setObjectName(_fromUtf8("rewindButton"))
        self.horizontalLayout_9.addWidget(self.rewindButton)
        self.playButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(44, 40))
        self.playButton.setMaximumSize(QtCore.QSize(44, 40))
        self.playButton.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Play")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon12)
        self.playButton.setIconSize(QtCore.QSize(32, 32))
        self.playButton.setFlat(True)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_9.addWidget(self.playButton)
        self.forwardButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forwardButton.sizePolicy().hasHeightForWidth())
        self.forwardButton.setSizePolicy(sizePolicy)
        self.forwardButton.setMinimumSize(QtCore.QSize(44, 40))
        self.forwardButton.setMaximumSize(QtCore.QSize(44, 40))
        self.forwardButton.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Forward")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon13)
        self.forwardButton.setIconSize(QtCore.QSize(32, 32))
        self.forwardButton.setFlat(True)
        self.forwardButton.setObjectName(_fromUtf8("forwardButton"))
        self.horizontalLayout_9.addWidget(self.forwardButton)
        self.endButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endButton.sizePolicy().hasHeightForWidth())
        self.endButton.setSizePolicy(sizePolicy)
        self.endButton.setMinimumSize(QtCore.QSize(44, 40))
        self.endButton.setMaximumSize(QtCore.QSize(44, 40))
        self.endButton.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/End")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.endButton.setIcon(icon14)
        self.endButton.setIconSize(QtCore.QSize(32, 32))
        self.endButton.setFlat(True)
        self.endButton.setObjectName(_fromUtf8("endButton"))
        self.horizontalLayout_9.addWidget(self.endButton)
        self.verticalLayout_2.addWidget(self.controlsFrame)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.countFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countFrame.sizePolicy().hasHeightForWidth())
        self.countFrame.setSizePolicy(sizePolicy)
        self.countFrame.setMinimumSize(QtCore.QSize(0, 42))
        self.countFrame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.countFrame.setFrameShape(QtGui.QFrame.Panel)
        self.countFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.countFrame.setObjectName(_fromUtf8("countFrame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.countFrame)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setMargin(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.countButton = QtGui.QPushButton(self.countFrame)
        self.countButton.setMinimumSize(QtCore.QSize(28, 24))
        self.countButton.setMaximumSize(QtCore.QSize(28, 24))
        self.countButton.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Count In")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.countButton.setIcon(icon15)
        self.countButton.setCheckable(False)
        self.countButton.setFlat(True)
        self.countButton.setObjectName(_fromUtf8("countButton"))
        self.horizontalLayout_4.addWidget(self.countButton)
        self.beatsBox = QtGui.QSpinBox(self.countFrame)
        self.beatsBox.setMaximumSize(QtCore.QSize(65, 20))
        self.beatsBox.setMaximum(16)
        self.beatsBox.setObjectName(_fromUtf8("beatsBox"))
        self.horizontalLayout_4.addWidget(self.beatsBox)
        self.label = QtGui.QLabel(self.countFrame)
        self.label.setMaximumSize(QtCore.QSize(10, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.bpmBox = QtGui.QSpinBox(self.countFrame)
        self.bpmBox.setMaximumSize(QtCore.QSize(65, 20))
        self.bpmBox.setMinimum(60)
        self.bpmBox.setMaximum(300)
        self.bpmBox.setProperty(_fromUtf8("value"), 120)
        self.bpmBox.setObjectName(_fromUtf8("bpmBox"))
        self.horizontalLayout_4.addWidget(self.bpmBox)
        self.horizontalLayout_3.addWidget(self.countFrame)
        self.toolsFrame = QtGui.QFrame(self.centralwidget)
        self.toolsFrame.setMinimumSize(QtCore.QSize(0, 42))
        self.toolsFrame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.toolsFrame.setFrameShape(QtGui.QFrame.Panel)
        self.toolsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.toolsFrame.setObjectName(_fromUtf8("toolsFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.toolsFrame)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(230, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.settingsButton = QtGui.QPushButton(self.toolsFrame)
        self.settingsButton.setMinimumSize(QtCore.QSize(28, 24))
        self.settingsButton.setMaximumSize(QtCore.QSize(28, 24))
        self.settingsButton.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Settings")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon16)
        self.settingsButton.setFlat(True)
        self.settingsButton.setObjectName(_fromUtf8("settingsButton"))
        self.horizontalLayout.addWidget(self.settingsButton)
        self.openButton = QtGui.QPushButton(self.toolsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMinimumSize(QtCore.QSize(28, 24))
        self.openButton.setMaximumSize(QtCore.QSize(28, 24))
        self.openButton.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Open")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon17)
        self.openButton.setIconSize(QtCore.QSize(32, 32))
        self.openButton.setFlat(True)
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.horizontalLayout.addWidget(self.openButton)
        self.horizontalLayout_3.addWidget(self.toolsFrame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionMark = QtGui.QAction(MainWindow)
        self.actionMark.setObjectName(_fromUtf8("actionMark"))
        self.actionHome = QtGui.QAction(MainWindow)
        self.actionHome.setObjectName(_fromUtf8("actionHome"))
        self.actionEnd = QtGui.QAction(MainWindow)
        self.actionEnd.setObjectName(_fromUtf8("actionEnd"))
        self.actionPreviousMark = QtGui.QAction(MainWindow)
        self.actionPreviousMark.setObjectName(_fromUtf8("actionPreviousMark"))
        self.actionNextMark = QtGui.QAction(MainWindow)
        self.actionNextMark.setObjectName(_fromUtf8("actionNextMark"))
        self.actionCountIn = QtGui.QAction(MainWindow)
        self.actionCountIn.setObjectName(_fromUtf8("actionCountIn"))
        self.actionMark_2 = QtGui.QAction(MainWindow)
        self.actionMark_2.setObjectName(_fromUtf8("actionMark_2"))
        self.actionSelection = QtGui.QAction(MainWindow)
        self.actionSelection.setObjectName(_fromUtf8("actionSelection"))
        self.actionLoop = QtGui.QAction(MainWindow)
        self.actionLoop.setObjectName(_fromUtf8("actionLoop"))
        self.actionToggleMute = QtGui.QAction(MainWindow)
        self.actionToggleMute.setObjectName(_fromUtf8("actionToggleMute"))
        self.actionVolumeUp = QtGui.QAction(MainWindow)
        self.actionVolumeUp.setObjectName(_fromUtf8("actionVolumeUp"))
        self.actionVolumeDown = QtGui.QAction(MainWindow)
        self.actionVolumeDown.setObjectName(_fromUtf8("actionVolumeDown"))
        self.actionZoomIn = QtGui.QAction(MainWindow)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoomOut = QtGui.QAction(MainWindow)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionPageDown = QtGui.QAction(MainWindow)
        self.actionPageDown.setObjectName(_fromUtf8("actionPageDown"))
        self.actionPageUp = QtGui.QAction(MainWindow)
        self.actionPageUp.setObjectName(_fromUtf8("actionPageUp"))
        self.actionSetBegin = QtGui.QAction(MainWindow)
        self.actionSetBegin.setObjectName(_fromUtf8("actionSetBegin"))
        self.actionSetEnd = QtGui.QAction(MainWindow)
        self.actionSetEnd.setObjectName(_fromUtf8("actionSetEnd"))
        self.actionSetBegin_2 = QtGui.QAction(MainWindow)
        self.actionSetBegin_2.setObjectName(_fromUtf8("actionSetBegin_2"))
        self.actionSetEnd_2 = QtGui.QAction(MainWindow)
        self.actionSetEnd_2.setObjectName(_fromUtf8("actionSetEnd_2"))
        self.actionTrack = QtGui.QAction(MainWindow)
        self.actionTrack.setObjectName(_fromUtf8("actionTrack"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.playButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionPlay.trigger)
        QtCore.QObject.connect(self.startButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionHome.trigger)
        QtCore.QObject.connect(self.endButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionEnd.trigger)
        QtCore.QObject.connect(self.actionMark_2, QtCore.SIGNAL(_fromUtf8("triggered()")), self.actionMark.trigger)
        QtCore.QObject.connect(self.actionSetBegin_2, QtCore.SIGNAL(_fromUtf8("triggered()")), self.actionSetBegin.trigger)
        QtCore.QObject.connect(self.actionSetEnd_2, QtCore.SIGNAL(_fromUtf8("triggered()")), self.actionSetEnd.trigger)
        QtCore.QObject.connect(self.zoomInButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionZoomIn.trigger)
        QtCore.QObject.connect(self.zoomOutButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionZoomOut.trigger)
        QtCore.QObject.connect(self.setBeginButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSetBegin.trigger)
        QtCore.QObject.connect(self.prevMarkButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionPreviousMark.trigger)
        QtCore.QObject.connect(self.markButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionMark.trigger)
        QtCore.QObject.connect(self.nextMarkButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionNextMark.trigger)
        QtCore.QObject.connect(self.setEndButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSetEnd.trigger)
        QtCore.QObject.connect(self.openButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionOpen.trigger)
        QtCore.QObject.connect(self.countButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionCountIn.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Listen, Learn, Play", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Mute [Esc]</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Volume Up [Ctrl++]</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Volume Down [Ctrl+-]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.positionIndicator.setText(QtGui.QApplication.translate("MainWindow", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.dividerLabel.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.totalLabel.setText(QtGui.QApplication.translate("MainWindow", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.loopButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Repeat endlessly or play once</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[L]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.selectionButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Switch between playing song and selection</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[S]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.trackButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Track the current time in the view window</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[T]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Zoom In</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[+]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Zoom Out</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[-]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.setBeginButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Set the beginning of the selection</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Cntrl+Return]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMarkButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Jump to the previous mark</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Up]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.markButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Add/delete a mark at the current position</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Return]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.nextMarkButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Jump to the next mark</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Down]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.setEndButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Set the end of the selection</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Alt+Return]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">To Start</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Home]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rewindButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Rewind", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Play</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Space]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.forwardButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Fast Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.endButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">To End</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[End]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.countButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Count in to playing</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Ctril+Space]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.beatsBox.setSuffix(QtGui.QApplication.translate("MainWindow", " beats", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "at", None, QtGui.QApplication.UnicodeUTF8))
        self.bpmBox.setSuffix(QtGui.QApplication.translate("MainWindow", " bpm", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Open a new music file</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[Ctrl+N]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark.setText(QtGui.QApplication.translate("MainWindow", "mark", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setText(QtGui.QApplication.translate("MainWindow", "home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setShortcut(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnd.setText(QtGui.QApplication.translate("MainWindow", "end", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnd.setShortcut(QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreviousMark.setText(QtGui.QApplication.translate("MainWindow", "previousMark", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreviousMark.setShortcut(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextMark.setText(QtGui.QApplication.translate("MainWindow", "nextMark", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextMark.setShortcut(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCountIn.setText(QtGui.QApplication.translate("MainWindow", "countIn", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCountIn.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_2.setText(QtGui.QApplication.translate("MainWindow", "mark", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark_2.setShortcut(QtGui.QApplication.translate("MainWindow", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelection.setText(QtGui.QApplication.translate("MainWindow", "selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelection.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoop.setText(QtGui.QApplication.translate("MainWindow", "loop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoop.setShortcut(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleMute.setText(QtGui.QApplication.translate("MainWindow", "toggleMute", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleMute.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVolumeUp.setText(QtGui.QApplication.translate("MainWindow", "volumeUp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVolumeUp.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl++", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVolumeDown.setText(QtGui.QApplication.translate("MainWindow", "volumeDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVolumeDown.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "zoomIn", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setShortcut(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "zoomOut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setShortcut(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPageDown.setText(QtGui.QApplication.translate("MainWindow", "pageDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPageDown.setShortcut(QtGui.QApplication.translate("MainWindow", "PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPageUp.setText(QtGui.QApplication.translate("MainWindow", "pageUp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPageUp.setShortcut(QtGui.QApplication.translate("MainWindow", "PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetBegin.setText(QtGui.QApplication.translate("MainWindow", "setBegin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetBegin.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetEnd.setText(QtGui.QApplication.translate("MainWindow", "setEnd", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetEnd.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetBegin_2.setText(QtGui.QApplication.translate("MainWindow", "setBegin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetBegin_2.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetEnd_2.setText(QtGui.QApplication.translate("MainWindow", "setEnd", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetEnd_2.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTrack.setText(QtGui.QApplication.translate("MainWindow", "track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTrack.setShortcut(QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
import llp_rc
