# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike_2\Eclipse workspace\LLP\src\llp.ui'
#
# Created: Thu Jan 26 21:24:19 2012
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(758, 174)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(758, 174))
        MainWindow.setMaximumSize(QtCore.QSize(758, 174))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.volumeSlider.setMaximumSize(QtCore.QSize(44, 10000))
        self.volumeSlider.setOrientation(QtCore.Qt.Vertical)
        self.volumeSlider.setMuteVisible(True)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.verticalLayout.addWidget(self.volumeSlider)
        self.openButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMinimumSize(QtCore.QSize(44, 40))
        self.openButton.setMaximumSize(QtCore.QSize(44, 40))
        self.openButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Open")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon)
        self.openButton.setIconSize(QtCore.QSize(32, 32))
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.verticalLayout.addWidget(self.openButton)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.markFrame = QtGui.QFrame(self.centralwidget)
        self.markFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.markFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.markFrame.setObjectName(_fromUtf8("markFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.markFrame)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.markButton = QtGui.QPushButton(self.markFrame)
        self.markButton.setObjectName(_fromUtf8("markButton"))
        self.verticalLayout_5.addWidget(self.markButton)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.prevMarkButton = QtGui.QPushButton(self.markFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMarkButton.sizePolicy().hasHeightForWidth())
        self.prevMarkButton.setSizePolicy(sizePolicy)
        self.prevMarkButton.setMinimumSize(QtCore.QSize(28, 24))
        self.prevMarkButton.setMaximumSize(QtCore.QSize(28, 24))
        self.prevMarkButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/PreviousMark")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevMarkButton.setIcon(icon1)
        self.prevMarkButton.setObjectName(_fromUtf8("prevMarkButton"))
        self.horizontalLayout_7.addWidget(self.prevMarkButton)
        self.nextMarkButton = QtGui.QPushButton(self.markFrame)
        self.nextMarkButton.setMinimumSize(QtCore.QSize(28, 24))
        self.nextMarkButton.setMaximumSize(QtCore.QSize(28, 24))
        self.nextMarkButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/NextMark")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextMarkButton.setIcon(icon2)
        self.nextMarkButton.setObjectName(_fromUtf8("nextMarkButton"))
        self.horizontalLayout_7.addWidget(self.nextMarkButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem = QtGui.QSpacerItem(20, 90, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_10.addWidget(self.markFrame)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seekSlider.sizePolicy().hasHeightForWidth())
        self.seekSlider.setSizePolicy(sizePolicy)
        self.seekSlider.setMinimumSize(QtCore.QSize(400, 20))
        self.seekSlider.setMaximumSize(QtCore.QSize(408, 20))
        self.seekSlider.setIconVisible(False)
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.verticalLayout_3.addWidget(self.seekSlider)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.markView = QtGui.QGraphicsView(self.centralwidget)
        self.markView.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.markView.sizePolicy().hasHeightForWidth())
        self.markView.setSizePolicy(sizePolicy)
        self.markView.setMinimumSize(QtCore.QSize(394, 71))
        self.markView.setMaximumSize(QtCore.QSize(390, 71))
        self.markView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.markView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.markView.setObjectName(_fromUtf8("markView"))
        self.horizontalLayout_8.addWidget(self.markView)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.controlsFrame = QtGui.QFrame(self.centralwidget)
        self.controlsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.controlsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.controlsFrame.setObjectName(_fromUtf8("controlsFrame"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.controlsFrame)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.startButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(44, 40))
        self.startButton.setMaximumSize(QtCore.QSize(44, 40))
        self.startButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Start")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon3)
        self.startButton.setIconSize(QtCore.QSize(32, 32))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_9.addWidget(self.startButton)
        self.rewindButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rewindButton.sizePolicy().hasHeightForWidth())
        self.rewindButton.setSizePolicy(sizePolicy)
        self.rewindButton.setMinimumSize(QtCore.QSize(44, 40))
        self.rewindButton.setMaximumSize(QtCore.QSize(44, 40))
        self.rewindButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Rewind")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindButton.setIcon(icon4)
        self.rewindButton.setIconSize(QtCore.QSize(32, 32))
        self.rewindButton.setObjectName(_fromUtf8("rewindButton"))
        self.horizontalLayout_9.addWidget(self.rewindButton)
        self.playButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(44, 40))
        self.playButton.setMaximumSize(QtCore.QSize(44, 40))
        self.playButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Play")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon5)
        self.playButton.setIconSize(QtCore.QSize(32, 32))
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_9.addWidget(self.playButton)
        self.forwardButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forwardButton.sizePolicy().hasHeightForWidth())
        self.forwardButton.setSizePolicy(sizePolicy)
        self.forwardButton.setMinimumSize(QtCore.QSize(44, 40))
        self.forwardButton.setMaximumSize(QtCore.QSize(44, 40))
        self.forwardButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Forward")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon6)
        self.forwardButton.setIconSize(QtCore.QSize(32, 32))
        self.forwardButton.setObjectName(_fromUtf8("forwardButton"))
        self.horizontalLayout_9.addWidget(self.forwardButton)
        self.endButton = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endButton.sizePolicy().hasHeightForWidth())
        self.endButton.setSizePolicy(sizePolicy)
        self.endButton.setMinimumSize(QtCore.QSize(44, 40))
        self.endButton.setMaximumSize(QtCore.QSize(44, 40))
        self.endButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/End")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.endButton.setIcon(icon7)
        self.endButton.setIconSize(QtCore.QSize(32, 32))
        self.endButton.setObjectName(_fromUtf8("endButton"))
        self.horizontalLayout_9.addWidget(self.endButton)
        self.horizontalLayout.addWidget(self.controlsFrame)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.positionIndicator = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionIndicator.sizePolicy().hasHeightForWidth())
        self.positionIndicator.setSizePolicy(sizePolicy)
        self.positionIndicator.setMinimumSize(QtCore.QSize(0, 20))
        self.positionIndicator.setMaximumSize(QtCore.QSize(16777215, 20))
        self.positionIndicator.setObjectName(_fromUtf8("positionIndicator"))
        self.horizontalLayout_2.addWidget(self.positionIndicator)
        self.dividerLabel = QtGui.QLabel(self.centralwidget)
        self.dividerLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.dividerLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.dividerLabel.setObjectName(_fromUtf8("dividerLabel"))
        self.horizontalLayout_2.addWidget(self.dividerLabel)
        self.totalLabel = QtGui.QLabel(self.centralwidget)
        self.totalLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.totalLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.totalLabel.setObjectName(_fromUtf8("totalLabel"))
        self.horizontalLayout_2.addWidget(self.totalLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.rightFrame = QtGui.QFrame(self.centralwidget)
        self.rightFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.rightFrame.setObjectName(_fromUtf8("rightFrame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.rightFrame)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.setBeginButton = QtGui.QPushButton(self.rightFrame)
        self.setBeginButton.setMinimumSize(QtCore.QSize(60, 23))
        self.setBeginButton.setObjectName(_fromUtf8("setBeginButton"))
        self.horizontalLayout_6.addWidget(self.setBeginButton)
        spacerItem4 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.setEndButton = QtGui.QPushButton(self.rightFrame)
        self.setEndButton.setMinimumSize(QtCore.QSize(60, 23))
        self.setEndButton.setObjectName(_fromUtf8("setEndButton"))
        self.horizontalLayout_6.addWidget(self.setEndButton)
        spacerItem5 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem6 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.loopButton = QtGui.QPushButton(self.rightFrame)
        self.loopButton.setMinimumSize(QtCore.QSize(60, 23))
        self.loopButton.setMaximumSize(QtCore.QSize(109, 23))
        self.loopButton.setCheckable(True)
        self.loopButton.setObjectName(_fromUtf8("loopButton"))
        self.horizontalLayout_5.addWidget(self.loopButton)
        spacerItem7 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.selectionButton = QtGui.QPushButton(self.rightFrame)
        self.selectionButton.setMinimumSize(QtCore.QSize(60, 23))
        self.selectionButton.setMaximumSize(QtCore.QSize(109, 23))
        self.selectionButton.setCheckable(True)
        self.selectionButton.setObjectName(_fromUtf8("selectionButton"))
        self.horizontalLayout_5.addWidget(self.selectionButton)
        spacerItem8 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem9 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.countButton = QtGui.QPushButton(self.rightFrame)
        self.countButton.setMinimumSize(QtCore.QSize(75, 23))
        self.countButton.setCheckable(False)
        self.countButton.setFlat(False)
        self.countButton.setObjectName(_fromUtf8("countButton"))
        self.horizontalLayout_4.addWidget(self.countButton)
        spacerItem10 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.beatsBox = QtGui.QSpinBox(self.rightFrame)
        self.beatsBox.setMaximumSize(QtCore.QSize(65, 20))
        self.beatsBox.setMaximum(16)
        self.beatsBox.setObjectName(_fromUtf8("beatsBox"))
        self.horizontalLayout_3.addWidget(self.beatsBox)
        self.label = QtGui.QLabel(self.rightFrame)
        self.label.setMaximumSize(QtCore.QSize(10, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.bpmBox = QtGui.QSpinBox(self.rightFrame)
        self.bpmBox.setMaximumSize(QtCore.QSize(65, 20))
        self.bpmBox.setMinimum(60)
        self.bpmBox.setMaximum(300)
        self.bpmBox.setProperty(_fromUtf8("value"), 120)
        self.bpmBox.setObjectName(_fromUtf8("bpmBox"))
        self.horizontalLayout_3.addWidget(self.bpmBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.rightFrame)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.openButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionOpen.trigger)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Listen, Learn, Play", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a new music file", None, QtGui.QApplication.UnicodeUTF8))
        self.markButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Add/delete a mark at the current position", None, QtGui.QApplication.UnicodeUTF8))
        self.markButton.setText(QtGui.QApplication.translate("MainWindow", "Mark", None, QtGui.QApplication.UnicodeUTF8))
        self.prevMarkButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Jump to the previous mark", None, QtGui.QApplication.UnicodeUTF8))
        self.nextMarkButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Jump to the next mark", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setToolTip(QtGui.QApplication.translate("MainWindow", "To Start", None, QtGui.QApplication.UnicodeUTF8))
        self.rewindButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Rewind", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.forwardButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Fast Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.endButton.setToolTip(QtGui.QApplication.translate("MainWindow", "To End", None, QtGui.QApplication.UnicodeUTF8))
        self.positionIndicator.setText(QtGui.QApplication.translate("MainWindow", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.dividerLabel.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.totalLabel.setText(QtGui.QApplication.translate("MainWindow", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.setBeginButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the beginning of the selection", None, QtGui.QApplication.UnicodeUTF8))
        self.setBeginButton.setText(QtGui.QApplication.translate("MainWindow", "Begin", None, QtGui.QApplication.UnicodeUTF8))
        self.setEndButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the end of the selection", None, QtGui.QApplication.UnicodeUTF8))
        self.setEndButton.setText(QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.loopButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Repeat endlessly", None, QtGui.QApplication.UnicodeUTF8))
        self.loopButton.setText(QtGui.QApplication.translate("MainWindow", "Once", None, QtGui.QApplication.UnicodeUTF8))
        self.selectionButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Switch between playing song and selection", None, QtGui.QApplication.UnicodeUTF8))
        self.selectionButton.setText(QtGui.QApplication.translate("MainWindow", "Song", None, QtGui.QApplication.UnicodeUTF8))
        self.countButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Count in to playing", None, QtGui.QApplication.UnicodeUTF8))
        self.countButton.setText(QtGui.QApplication.translate("MainWindow", "Count In", None, QtGui.QApplication.UnicodeUTF8))
        self.beatsBox.setSuffix(QtGui.QApplication.translate("MainWindow", " beats", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "at", None, QtGui.QApplication.UnicodeUTF8))
        self.bpmBox.setSuffix(QtGui.QApplication.translate("MainWindow", " bpm", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
import llp_rc
